config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors, controllers: {registrations: "doctors/registrations"} 

  root 'start#index'
 
  resources :doctors, only: [:show]

  get "autocomplete_patient_name", controller: "application"

  resources :patients, only: [:show]
  resources :invoices
  get 'search_patient'  => 'application#search_patient'
  post 'search_patient'  => 'application#search_patient'

  resources :ophtalmology_templates do
    resources :prescriptions, module: :ophtalmology_templates
    resources :template_photos, module: :ophtalmology_templates
    resources :template_files, module: :ophtalmology_templates
    resources :patients, module: :ophtalmology_templates
  end

  resources :general_templates do
    resources :general_annexes, except: [:index]
    resources :prescriptions, module: :general_templates
    resources :template_photos, module: :general_templates
    resources :template_files, module: :general_templates
    resources :patients, module: :general_templates
  end
  resources :gynecology_templates do
    resources :gynecology_annexes, except: [:index]
    resources :prescriptions, module: :gynecology_templates
    resources :template_photos, module: :gynecology_templates
    resources :template_files, module: :gynecology_templates
    resources :patients, module: :gynecology_templates
    resources :pregnancy_evolutions, except: [:index]
    resources :pregnancy_notes, except: [:index]
    
  end

  resources :doctors, only: [:show, :edit, :update, :destroy]
  resources :template_plans
  resources :plans, only: [:show] do
    collection do
      get :save_template_plan
      post :save_template_plan
    end
  end

  resources :payments, except: [:index, :show, :edit, :update, :destroy, :new, :create] do
    collection do
      get :accept
      put :accept
      get :cancel
      put :cancel
    end
  end
  get '/add_template_plan', to: "plans#add_template_plan", :as => "add_template_plan"
  get '/doctor_plan', to: "plans#doctor_plan", :as => "doctor_plan"
  get '/template_plan_history', to: "plans#template_plan_history", :as => "template_plan_history"

  get '/doctor_payment_panel', to: "doctors#doctor_payment_panel", :as => "doctor_payment_panel"
  get '/doctor_panel', to: "doctors#panel", :as => "doctor_panel"
  
  get '/admin_panel', to: "admins#admin_panel", :as => "admin_panel"
  get '/admin_templates_panel', to: "admins#admin_templates_panel", :as => "admin_templates_panel"
  get '/overdue_template_plans', to: "admins#overdue_template_plans", :as => "overdue_template_plans"
  get '/all_gynecologists', to: "admins#all_gynecologists", :as => "all_gynecologists"
  get '/all_ophthalmologists', to: "admins#all_ophthalmologists", :as => "all_ophthalmologists"
  get '/show_doctor', to: "admins#show_doctor", :as => "show_doctor"
  get '/show_invoice_data', to: "admins#show_invoice_data", :as => "show_invoice_data"

  resources :start, only: [:index]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contraceptive.rb
class Contraceptive < ActiveRecord::Base
	belongs_to :gynecology_templates

	validates :name, presence: true

	def to_s
		name
	end
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ophtalmology_templates, dependent: :delete_all
  has_many :gynecology_templates, dependent: :delete_all
  has_many :general_templates, dependent: :delete_all

  has_many :doctor_pictures, dependent: :delete_all
  has_many :patients, dependent: :delete_all
  has_many :plans
  has_many :invoices, dependent: :delete_all
end

app/models/doctor_picture.rb
class DoctorPicture < ActiveRecord::Base
  belongs_to :doctor
end

app/models/general_annex.rb
class GeneralAnnex < ActiveRecord::Base
  belongs_to :general_template
  validates :annex, presence: true
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :doctor

	validate :validate_favorite

	private
		def validate_favorite
			isFavorite = false			
			self.doctor.invoices.each do |invoice|
				if invoice.favorite == true 
					isFavorite = true
				end
			end

			if isFavorite == true and self.favorite == true
				errors.add(:base, "Ya tienes unos datos de facturación marcados como favoritos, si quieres marcar estos como favoritos debes de modificar los otros primero.")
			end
		end
end

app/models/labor.rb
class Labor < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :doctor
	belongs_to :templatable, polymorphic: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :plan
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :doctor
	has_many :payments
	has_many :plan_elements
  	has_many :template_plan, :through => :plan_elements, :source => :element, :source_type => 'TemplatePlan'
  	has_many :site_plan, :through => :plan_elements, :source => :element, :source_type => 'SitePlan'
end

app/models/plan_element.rb
class PlanElement < ActiveRecord::Base

	belongs_to :plan
 	 belongs_to :element, :polymorphic => true
end

app/models/pregnancy.rb
class Pregnancy < ActiveRecord::Base
	belongs_to :gynecology_template
end

app/models/pregnancy_note.rb
class PregnancyNote < ActiveRecord::Base
	belongs_to :gynecology_template
	validates :note, presence: true
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
	belongs_to :prescriptable, :polymorphic => true
end

app/models/site_plan.rb
class SitePlan < ActiveRecord::Base

	has_one :plan_element, :as =>:element
  	has_one :plan, :through => :plan_elements
end

app/models/template_file.rb
class TemplateFile < ActiveRecord::Base
	belongs_to :fileable, polymorphic: true
end

app/models/template_photo.rb
class TemplatePhoto < ActiveRecord::Base
	belongs_to :photable, polymorphic: true
end

app/models/template_plan.rb
class TemplatePlan < ActiveRecord::Base
	validates :name, :monthly_cost, :anual_discount, :description, :max_files, presence: true
	before_save :set_annual_cost

	has_one :plan_element, :as =>:element
 	has_one :plan, :through => :plan_elements
	
	private
		def set_annual_cost
			self.anual_cost = (self.monthly_cost * 12) * ( (100 - self.anual_discount)/100 )
		end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/admins/_doctors.html.erb
<%= link_to doctor.name, show_doctor_path(doctor) %>

app/views/admins/admin_panel.html.erb
<h1>Admin Panel</h1>

<%= link_to "Administrar Cuentas de Expedientes", admin_templates_panel_path %><br/>
<%= link_to "Ginecológos", all_gynecologists_path %><br/>
<%= link_to "Oftalmológos", all_ophthalmologists_path  %><br/>

app/views/admins/admin_templates_panel.html.erb
<h1>Administrador de Cuentas de Expedientes.</h1>


<% if current_admin.superadmin? %>	
	<%= link_to "Planes de Expedientes", template_plans_path %><br/>
<% end %>

<%= link_to "Añadir o Cambiar Plan de Expediente", add_template_plan_path %><br/>
<%= link_to "Planes de expedientes vencidos (Período de Gracia)", overdue_template_plans_path %><br/>

app/views/admins/all_gynecologists.html.erb
<h1>Ginecológos</h1>
<%= link_to "Registrar Doctor", new_doctor_registration_path %><br/>

<% @gynecologists.each do |doctor| %>
	<%= render 'doctors', doctor: doctor %>
<% end %>

app/views/admins/all_ophthalmologists.html.erb
<h1>Oftalmológos</h1>

<%= link_to "Registrar Doctor", new_doctor_registration_path %><br/>
<% @ophthalmologists.each do |doctor| %>
	<%= render 'doctors', doctor: doctor %>
<% end %>

app/views/admins/overdue_template_plans.html.erb
<h1> Planes de Expedientes que vencieron hoy</h1>
<p>Estos planes entran en un período de gracia de 15 días antes de su cancelación total, contacta a los doctores para que realicen su pago o confirmalo para que no se cancele su cuenta.</p>


<% @overdue_payments.each do |payment| %>
	Doctor: <%= link_to payment.plan.doctor.name, show_doctor_path(payment.plan.doctor) %> <%= link_to "Ver plan", payment.plan %> <br/>

<% end %>

app/views/admins/show_doctor.html.erb
<p><%= @doctor.name %></p>
<%= link_to "EDITAR", edit_doctor_path(@doctor) %><br>
<p><%= @doctor.email %></p>
<p><%= @doctor.country %></p>
<p><%= @doctor.state %></p>
<p><%= @doctor.city %></p>
<p><%= @doctor.phone %></p>
<p><%= @doctor.facebook %></p>
<p><%= @doctor.website %></p>
<p><%= @doctor.profession %></p>
<p><%= @doctor.speciality %></p>

<h3>  Planes Activos </h3>

<% @doctor.plans.each do |plan| %>
	<% plan.plan_elements.each do |element| %>
		<%= link_to element.element.name, plan %>
	<% end %>
<% end %>

<h3>Acciones</h3>

<%= link_to "Ver Historial de Planes de Expediente", template_plan_history_path(@doctor) %><br/>
 

<h6>Datos de Facturación</h6>

<% @doctor.invoices.each do |invoice| %>
	<% if invoice.favorite? %>
		<%= invoice.rfc %><br/>
		<%= invoice.name %><br/>
		<%= invoice.address1 %><br/>
		<%= invoice.num_ext %><br/>
		<%= invoice.num_int %><br/>
		<%= invoice.address2 %><br/>
		<%= invoice.city %><br/>
		<%= invoice.state %><br/>
		<%= invoice.country %><br/>
	<% end %>
<% end %>