config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors, controllers: {registrations: "doctors/registrations"} 

  root 'start#index'
 
  resources :doctors, only: [:show]

  get "autocomplete_patient_name", controller: "application"

  resources :patients, only: [:show]
  resources :invoices
  get 'search_patient'  => 'application#search_patient'
  post 'search_patient'  => 'application#search_patient'

  resources :ophtalmology_templates do
    resources :prescriptions, module: :ophtalmology_templates
    resources :template_photos, module: :ophtalmology_templates
    resources :template_files, module: :ophtalmology_templates
    resources :patients, module: :ophtalmology_templates
  end

  resources :general_templates do
    resources :general_annexes, except: [:index]
    resources :prescriptions, module: :general_templates
    resources :template_photos, module: :general_templates
    resources :template_files, module: :general_templates
    resources :patients, module: :general_templates
  end
  resources :gynecology_templates do
    resources :gynecology_annexes, except: [:index]
    resources :prescriptions, module: :gynecology_templates
    resources :template_photos, module: :gynecology_templates
    resources :template_files, module: :gynecology_templates
    resources :patients, module: :gynecology_templates
    resources :pregnancy_evolutions, except: [:index]
    resources :pregnancy_notes, except: [:index]
    
  end

  resources :doctors, only: [:show, :edit, :update, :destroy]
  resources :template_plans
  resources :plans, only: [:show] do
    collection do
      get :save_template_plan
      post :save_template_plan
    end
  end

  resources :payments, except: [:index, :show, :edit, :update, :destroy, :new, :create] do
    collection do
      get :accept
      put :accept
      get :cancel
      put :cancel
    end
  end
  get '/add_template_plan', to: "plans#add_template_plan", :as => "add_template_plan"
  get '/doctor_plan', to: "plans#doctor_plan", :as => "doctor_plan"
  get '/template_plan_history', to: "plans#template_plan_history", :as => "template_plan_history"

  get '/doctor_payment_panel', to: "doctors#doctor_payment_panel", :as => "doctor_payment_panel"
  get '/doctor_panel', to: "doctors#panel", :as => "doctor_panel"
  
  get '/admin_panel', to: "admins#admin_panel", :as => "admin_panel"
  get '/admin_templates_panel', to: "admins#admin_templates_panel", :as => "admin_templates_panel"
  get '/overdue_template_plans', to: "admins#overdue_template_plans", :as => "overdue_template_plans"
  get '/all_gynecologists', to: "admins#all_gynecologists", :as => "all_gynecologists"
  get '/all_ophthalmologists', to: "admins#all_ophthalmologists", :as => "all_ophthalmologists"
  get '/show_doctor', to: "admins#show_doctor", :as => "show_doctor"
  get '/show_invoice_data', to: "admins#show_invoice_data", :as => "show_invoice_data"

  resources :start, only: [:index]

end

app/models/gynecology_template.rb
class GynecologyTemplate < ActiveRecord::Base
	belongs_to :doctor
	has_many :contraceptives, dependent: :delete_all
	accepts_nested_attributes_for :contraceptives, reject_if: proc { |attributes| attributes['name'].blank? }, :allow_destroy => true

	has_many :pregnancies, dependent: :delete_all
	accepts_nested_attributes_for :pregnancies, reject_if: proc { |attributes| attributes['pregnancy_number'].blank? }, :allow_destroy => true
	
	has_many :gynecology_annexes, dependent: :delete_all
	has_many :prescriptions, :as => :prescriptable, dependent: :delete_all
	has_many :template_photos, :as => :photable, dependent: :delete_all
	has_many :template_files, :as => :fileable, dependent: :delete_all
	has_one :patient, as: :templatable, dependent: :delete
	#accepts_nested_attributes_for :patients, reject_if: proc { |attributes| attributes['name'].blank? }, :allow_destroy => true
	
	before_create :set_register_number
	has_many :pregnancy_evolutions
	has_many :pregnancy_notes
	

	def to_s
		name
	end

	private
		def set_register_number
			total_count = self.doctor.gynecology_templates.count
			self.register = total_count+1
		end
end

app/controllers/gynecology_templates/prescriptions_controller.rb
class GynecologyTemplates::PrescriptionsController < PrescriptionsController
  before_action :set_prescriptable
  
  private

    def set_prescriptable
      @prescriptable = GynecologyTemplate.find(params[:gynecology_template_id])
      authenticate_doctor_for_template(@prescriptable)
    end
end

app/controllers/gynecology_templates/template_files_controller.rb
class GynecologyTemplates::TemplateFilesController < TemplateFilesController
  before_action :set_fileable

  private

    def set_fileable
      @fileable = GynecologyTemplate.find(params[:gynecology_template_id])
      authenticate_doctor_for_template(@fileable)
    end
end

app/controllers/gynecology_templates/template_photos_controller.rb
class GynecologyTemplates::TemplatePhotosController < TemplatePhotosController
  before_action :set_photable

  private

    def set_photable
      @photable = GynecologyTemplate.find(params[:gynecology_template_id])
      authenticate_doctor_for_template(@photable)
    end
end

app/controllers/gynecology_templates_controller.rb
class GynecologyTemplatesController < ApplicationController
	before_action :authenticate_doctor!
	before_action :check_plan_limit, only: [:new, :create]
	before_action :check_payment_for_templates!
	before_action :set_gynecology_template, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_doctor_for_gynecology_template, only: [:show, :edit, :update, :destroy]
	before_action :find_patient, only: [:edit, :update]
	
	def index
		@gynecology_templates = GynecologyTemplate.where(doctor: current_doctor)
	end

	def new
		@gynecology_template = GynecologyTemplate.new
		1.times { @gynecology_template.contraceptives.build }
		1.times { @gynecology_template.pregnancies.build }
	end
	def create
		@gynecology_template = GynecologyTemplate.new(gynecology_template_params)
		@gynecology_template.doctor = current_doctor
		if @gynecology_template.save
			Patient.create doctor: current_doctor, name: params[:gynecology_template][:patients][:name], birth_date: params[:gynecology_template][:patients][:birth_date], sex: params[:gynecology_template][:patients][:sex], originary_from: params[:gynecology_template][:patients][:originary_from], ocupation: params[:gynecology_template][:patients][:ocupation], religion: params[:gynecology_template][:patients][:religion], address: params[:gynecology_template][:patients][:address], telephone: params[:gynecology_template][:patients][:telephone], email: params[:gynecology_template][:patients][:email], insurance_company: params[:gynecology_template][:patients][:insurance_company], insurance_policy: params[:gynecology_template][:patients][:insurance_policy], templatable_id: @gynecology_template.id, templatable_type: "GynecologyTemplate"
			flash[:notice] = "Expediente guardado."
			redirect_to @gynecology_template
		else
			flash[:alert] = "Expediente no guardado. Vuelve a intentar en un rato." 
			render action: "new"
		end
	end

	def show
		#set_current_gynecology_template(@gynecology_template)
	end

	def edit
		
	end

	def update
		if @gynecology_template.update(gynecology_template_params)
			@patient.update_attributes( name: params[:gynecology_template][:patients][:name], birth_date: params[:gynecology_template][:patients][:birth_date], sex: params[:gynecology_template][:patients][:sex], originary_from: params[:gynecology_template][:patients][:originary_from], ocupation: params[:gynecology_template][:patients][:ocupation], religion: params[:gynecology_template][:patients][:religion], address: params[:gynecology_template][:patients][:address], telephone: params[:gynecology_template][:patients][:telephone], email: params[:gynecology_template][:patients][:email], insurance_company: params[:gynecology_template][:patients][:insurance_company], insurance_policy: params[:gynecology_template][:patients][:insurance_policy])
			flash[:notice] = "Expediente guardado."
			redirect_to @gynecology_template
		else
			flash[:alert] = "Expediente no guardado. Vuelve a intentar en un rato." 
			render action: "edit"
		end
	end

	def destroy 
		@gynecology_template.destroy 
		flash[:notice] = "Expediente eliminado."
		redirect_to root_url
	end

	def search_patient
		@patient = Patient.find(params[:patient_id])
		redirect_to gynecology_template_path(@patient.templatable)
	end
	private
		def set_gynecology_template
			@gynecology_template = GynecologyTemplate.find(params[:id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "Expediente inexistente."
			redirect_to root_url
		end

		def gynecology_template_params
			params.require(:gynecology_template).permit(:register, :name, :email, :husband_name, :address, :telephone, :age, :husband_age, :marital_status, :ocupation, :husband_ocupation, :reason, :mother_background, :father_background, :grandparents_background, :siblings_background, :parents_siblings_background, :children_background,:husband_background,:personal_background,:diet,:smoking,:alergies,:drugs,:alcoholism,:inmunizations,:traumatics,:surgicals,:transfusions,:menarche,:rhythm,:dysmenorrhea,:circumcised_partner,:ivsa,:number_of_sexual_partners,:pms,:pms_duration,:gestate,:gestate_for,:c_section,:abortions,:ee,:induction,:gestational_age,:fum,:fup,:fua,:fuc,:fpp,:doc,:previous_preganancy_complications,:colposcopy,:sexual_habits,:fridigity,:dyspareunia,:menopause,:menopause_symptomatology,:leucorrea ,:leucorrea_treatment,:pregnancy_medication,:ta,:weight,:size,:habitus, :head, :neck, :torax, :abdomen, :limbs, :breasts_appearance, :symetry, :skin_abnormalities, :nipple, :abnormal_mass, :axillary_region, :ganglion_growth, :abnormal_secretion, :mastalgia, :external_aspect, :clitoris, :vulva, :pubic_hair, :himen, :introito, :perine, :vaginal_walls, :secreation_and_discharge, :cervix, :uterus_position, :uterus_consistency, :uterus_size, :uterus_form, :annexes, :speculoscopy, :internal_and_external_genitalia, :clinic_pelvimetry, :impression_diagnosis, :other_1, :other_2, :other_3, :other_4, :other_5, contraceptives_attributes: [:id, :name,:time,:tolerance, :_destroy], pregnancies_attributes: [:id, :pregnancy_number,:pregnancy_date,:abortion, :delivery, :induction, :ending, :newborn, :baby_weight, :baby_sex, :puerperium, :_destroy], patients_attributes: [ :name, :birth_date,:sex,:ocupation,:religion,:email,:address,:telephone,:insurance_company,:insurance_policy])
		end

		def find_patient
			@patient = Patient.find_by(templatable_id: @gynecology_template.id, templatable_type: "GynecologyTemplate")
		end	

		def check_plan_limit
			check_plan_limit_all_templates(current_doctor.gynecology_templates.count)
		end

		def authenticate_doctor_for_gynecology_template
			authenticate_doctor_for_elements(@gynecology_template)
		end

end

app/helpers/gynecology_templates_helper.rb
module GynecologyTemplatesHelper
	
end

app/views/gynecology_templates/_contraceptive_fields.html.erb
<div class="fields">
	<div class="double-field">
		<div>	
			<%= f.label :name %>
			<%= f.text_field :name, placeholder: true %>
		</div>
		<div>	
			<%= f.label :time %>
			<%= f.text_field :time, placeholder: true %>
		</div>
	</div>
	<div class="double-field">
		<div>	
			<%= f.label :tolerance %>
			<%= f.text_field :tolerance, placeholder: true %>
		</div>
		<div>	
			<%= f.hidden_field :_destroy %>
			<%= link_to_remove_fields "Eliminar", f %>
		</div>
	</div>
</div>

app/views/gynecology_templates/_pregnancy_fields.html.erb
<div class="fields">
	<div class="double-field">
		<div>
			<%= f.label :pregnancy_number %>
			<%= f.text_field :pregnancy_number, placeholder: true %> 
		</div>
		<div>
			<%= f.label :pregnancy_date %>
			<span class="date-select">
				<%= f.date_select :pregnancy_date, { :discard_day => true } %>
			</span>
		</div>
	</div>
	<div class="double-field">
		<div>
			<%= f.label :abortion %>
			<%= f.select :abortion, ['Esporádico', 'Provocado'] %>
		</div>
		<div>
			<%= f.label :delivery %>
			<%= f.select :delivery, ['Pretérmino', 'Término', 'PostTérmino'] %>
		</div>
	</div>
	<div class="double-field">
		<div>
			<%= f.label :induction %>
			<%= f.select :induction, ['Sí', 'No'] %>
		</div>
		<div>
			<%= f.label :ending %>
			<%= f.select :ending, ['Esporádico', 'Fórceps', 'Césarea'] %>
		</div>
	</div>
	<div class="double-field">
		<div>
			<%= f.label :newborn %>
			<%= f.select :newborn, ['Sí', 'No'] %>
		</div>
		<div>
			<%= f.label :rn %>
			<%= f.select :rn, ['Neonáto', 'Post-Neo'] %>
		</div>
	</div>
	<div class="double-field">
		<div>
			<%= f.label :baby_weight %>
			<%= f.text_field :baby_weight, placeholder: true %>
		</div>
		<div>
			<%= f.label :baby_sex %>
			<%= f.select :baby_sex, ['Femenino', 'Masculino'] %>
		</div>
	</div>
	<div class="double-field">
		<div>
			<%= f.label :puerperium %>
			<%= f.select :puerperium, ['Fís', 'Pat']%>
		</div>
		<div>
			<%= f.hidden_field :_destroy %>
			<%= link_to_remove_fields "Eliminar", f %>
		</div>
	</div>
</div>

app/views/gynecology_templates/edit.html.erb
<div class="center-content">
	<h4><%= t :new_expedient %></h4>
	<div class="form-container">
		<%= render 'form' %> 
	</div>
</div>

app/views/gynecology_templates/index.html.erb
<h4><%= t :expedients %></h4>
<div id="patient-index">
	<a>
		<div class="patient-container">
			<div class="patient-name">
				<label><%= t :name %></label>
			</div>
			<div class="patient-ocupation">
				<label><%= t :ocupation %></label>
			</div>
			<div class="patient-birth-date">
				<label><%= t :birth_date %></label>
			</div>
			<div class="patient-telephone">
				<label><%= t :telephone %></label>
			</div>
		</div>
	</a>
	<% @gynecology_templates.each do |expedient| %>
		<% expedient.id %>
		<% expedient.patients.each do |patient| %>
			<%= link_to expedient do %>
				<div class="patient-container">
					<div class="patient-name">
						<p><%= patient.name %></p>
					</div>
					<div class="patient-ocupation">
						<p><%= patient.ocupation %></p>
					</div>
					<div class="patient-birth-date">
						<p><%= patient.birth_date %></p>
					</div>
					<div class="patient-telephone">
						<p><%= patient.telephone %></p>
					</div>
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>
<%= javascript_include_tag "/assets/expedient/show" %>

app/views/gynecology_templates/new.html.erb
<div class="center-content">
	<!-- <h4><%= t :new_expedient %></h4> -->
	<div class="form-container">
		<%= render "form" %>
	</div>
</div>

app/views/gynecology_templates/show.html.erb
<label><%= t :register %></label>
<%= @gynecology_template.register %><br/>




	<h1><%= @gynecology_template.patient.name %></h1>
	<label><%= t :email %></label>
	<p><%= @gynecology_template.patient.email %></p>
	<label><%= t :name %></label>
	<p><%= @gynecology_template.patient.name %></p>
	<label><%= t :birth_date %></label>
	<p><%= @gynecology_template.patient.birth_date %></p>
	<label><%= t :sex %></label>
	<p><%= @gynecology_template.patient.sex %></p>
	<label><%= t :ocupation %></label>
	<p><%= @gynecology_template.patient.ocupation %></p>
	<label><%= t :religion %></label>
	<p><%= @gynecology_template.patient.religion %></p>
	<label><%= t :address %></label>
	<p><%= @gynecology_template.patient.address %></p>
	<label><%= t :telephone %></label>
	<p><%= @gynecology_template.patient.telephone %></p>
	<label><%= t :insurance_company %></label>
	<p><%= @gynecology_template.patient.insurance_company %></p>
	<label><%= t :insurance_policy %></label>
	<p><%= @gynecology_template.patient.insurance_policy %></p>


<%= link_to "Editar", edit_gynecology_template_path(@gynecology_template) %><br/>
<%= link_to "Eliminar", gynecology_template_path(@gynecology_template), method: :delete, data: {confirm: "¿Está seguro? Esta acción no se puede deshacer."} %><br/>

<%= link_to "Añadir Hoja de Evolución", new_gynecology_template_gynecology_annex_path(@gynecology_template) %><br/>
<%= link_to "Añadir Receta",  new_gynecology_template_prescription_path(@gynecology_template)%><br/>

<%= render 'prescriptions/prescriptions', prescriptable: @gynecology_template %>

<%= link_to "Añadir Foto",  new_gynecology_template_template_photo_path(@gynecology_template)%><br/>

<%= render 'template_photos/template_photos', photable: @gynecology_template %>


<%= link_to "Añadir Archivo",  new_gynecology_template_template_file_path(@gynecology_template)%><br/>

<%= render 'template_files/template_files', fileable: @gynecology_template %>

<%= link_to "Añadir Hoja de Evolución de Embarazo",   new_gynecology_template_pregnancy_evolution_path(@gynecology_template)%><br/>

<%= link_to "Añadir Nota Especial de Evolución",   new_gynecology_template_pregnancy_note_path(@gynecology_template)%><br/>

<h2>Historia Clínica</h2>


<label><%= t :husband_name %></label>
<%= @gynecology_template.husband_name %><br/>
<label><%= t :husband_age %></label>
<%= @gynecology_template.husband_age %><br/>
<label><%= t :marital_status %></label>
<%= @gynecology_template.marital_status %><br/>
<label><%= t :husband_ocupation %></label>
<%= @gynecology_template.husband_ocupation %><br/>
<label><%= t :reason%></label>
<%= @gynecology_template.reason %><br/>

<h3><%= t :family_background %></h3>
<label><%= t :mother_background %></label>
<%= @gynecology_template.mother_background %><br/>
<label><%= t :father_background %></label>
<%= @gynecology_template.father_background %><br/>
<label><%= t :grandparents_background %></label>
<%= @gynecology_template.grandparents_background %><br/>
<label><%= t :siblings_background %></label>
<%= @gynecology_template.siblings_background %><br/>
<label><%= t :parents_siblings_background %></label>
<%= @gynecology_template.parents_siblings_background %><br/>
<label><%= t :children_background %></label>
<%= @gynecology_template.children_background %><br/>
<label><%= t :husband_background %></label>
<%= @gynecology_template.husband_background %><br/>
<label><%= t :personal_background %></label>
<%= @gynecology_template.personal_background %><br/>
<label><%= t :diet %></label>
<%= @gynecology_template.diet %><br/>
<label><%= t :smoking %></label>
<%= @gynecology_template.smoking %><br/>
<label><%= t :alergies %></label>
<%= @gynecology_template.alergies %><br/>
<label><%= t :drugs %></label>
<%= @gynecology_template.drugs %><br/>
<label><%= t :alcoholism %></label>
<%= @gynecology_template.alcoholism %><br/>
<label><%= t :inmunizations %></label>
<%= @gynecology_template.inmunizations %><br/>
<label><%= t :traumatics %></label>
<%= @gynecology_template.traumatics %><br/>
<label><%= t :surgicals %></label>
<%= @gynecology_template.surgicals %><br/>
<label><%= t :transfusions %></label>
<%= @gynecology_template.transfusions %><br/>

<h3><%= t :gynecological_background %></h3>
<label><%= t :menarche%></label>
<%= @gynecology_template.menarche %><br/>
<label><%= t :rhythm %></label>
<%= @gynecology_template.rhythm %><br/>
<label><%= t :dysmenorrhea %></label>
<%= @gynecology_template.dysmenorrhea %><br/> 
<label><%= t :circumcised_partner %></label>
<%= @gynecology_template.circumcised_partner %><br/>
<label><%= t :ivsa %></label>
<%= @gynecology_template.ivsa %><br/>
<label><%= t :number_of_sexual_partners %></label>
<%= @gynecology_template.number_of_sexual_partners %><br/>
<label><%= t :pms %></label>
<%= @gynecology_template.pms  %><br/>
<label><%= t :pms_duration %></label>
<%= @gynecology_template.pms_duration %><br/>
<label><%= t :gestate %></label>
<%= @gynecology_template.gestate %><br/>
<label><%= t :gestate_for %></label>
<%= @gynecology_template.gestate_for %><br/>
<label><%= t :c_section %></label>
<%= @gynecology_template.c_section %><br/>
<label><%= t :abortions %></label>
<%= @gynecology_template.abortions %><br/>
<label><%= t :ee %></label>
<%= @gynecology_template.ee %><br/>

<label><%= t :fum %></label>
<%= @gynecology_template.fum %><br/>
<label><%= t :fup %></label>
<%= @gynecology_template.fup %><br/>
<label><%= t :fua %></label>
<%= @gynecology_template.fua %><br/>
<label><%= t :fuc %></label>
<%= @gynecology_template.fuc %><br/>
<label><%= t :fpp %></label>
<%= @gynecology_template.fpp %><br/>
<label><%= t :doc %></label>
<%= @gynecology_template.doc %><br/>
<label><%= t :previous_preganancy_complications %></label>
<%= @gynecology_template.previous_preganancy_complications %><br/>
<label><%= t :colposcopy %></label>
<%= @gynecology_template.colposcopy %><br/>

<h3><%= t :contraceptives %></h3>

 <% @gynecology_template.contraceptives.each do |contraceptive|  %>

	<label><%= t :contraceptive_name %></label>
	<%= contraceptive.name %><br/>
	<label><%= t :contraceptive_time %></label>
	<%= contraceptive.time %><br/>
	<label><%= t :contraceptive_tolerance %></label>
	<%= contraceptive.tolerance %><br/>
<% end %>

<h3><%= t :pregnancies %></h3>

 <% @gynecology_template.pregnancies.each do |pregnancy|  %>
	<label><%= t :pregnancy_number %></label>
	<%= pregnancy.pregnancy_number %><br/>
	<label><%= t :pregnancy_date %></label>
	<%= pregnancy.pregnancy_date %><br/>
	<label><%= t :pregnancy_abortion %></label>
	<%= pregnancy.abortion %><br/>
	<label><%= t :pregnancy_delivery %></label>
	<%= pregnancy.delivery %><br/>
	<label><%= t :pregnancy_induction %></label>
	<%= pregnancy.induction %><br/>
	<label><%= t :pregnancy_ending %></label>
	<%= pregnancy.ending %><br/>
	<label><%= t :pregnancy_newborn %></label>
	<%= pregnancy.newborn %><br/>
	<label><%= t :pregnancy_rn %></label>
	<%= pregnancy.rn %><br/>
	<label><%= t :pregnancy_baby_weight %></label>
	<%= pregnancy.baby_weight %><br/>
	<label><%= t :pregnancy_baby_sex %></label>
	<%= pregnancy.baby_sex %><br/>
	<label><%= t :pregnancy_puerperium %></label>
	<%= pregnancy.puerperium %><br/>
<% end %>
<br>

<label><%= t :sexual_habits %></label>
<%= @gynecology_template.sexual_habits %><br/>
<label><%= t :frigidity %></label>
<%= @gynecology_template.fridigity %><br/>
<label><%= t :dyspareunia %></label>
<%= @gynecology_template.dyspareunia %><br/>
<label><%= t :menopause %></label>
<%= @gynecology_template.menopause %><br/>
<label><%= t :menopause_symptomatology %></label>
<%= @gynecology_template.menopause_symptomatology %><br/>
<label><%= t :leucorrea %></label>
<%= @gynecology_template.leucorrea %><br/>
<label><%= t :leucorrea_treatment %></label>
<%= @gynecology_template.leucorrea_treatment %><br/>
<label><%= t :pregnancy_medication %></label>
<%= @gynecology_template.pregnancy_medication %><br/>


<h3><%= t :physical_exploration %></h3>
<label><%= t :ta %></label>
<%= @gynecology_template.ta %><br/>
<label><%= t :weight %></label>
<%= @gynecology_template.weight %><br/>
<label><%= t :size %></label>
<%= @gynecology_template.size %><br/>
<label><%= t :habitus %></label>
<%= @gynecology_template.habitus %><br/>
<label><%= t :head %></label>
<%= @gynecology_template.head %><br/>
<label><%= t :neck %></label>
<%= @gynecology_template.neck %><br/>
<label><%= t :torax %></label>
<%= @gynecology_template.torax %><br/>
<label><%= t :abdomen %></label>
<%= @gynecology_template.abdomen %><br/>
<label><%= t :limbs %></label>
<%= @gynecology_template.limbs %><br/>

<h3><%= t :breast_exploration%></h3>
<label><%= t :breasts_appearance %></label>
<%= @gynecology_template.breasts_appearance %><br/>
<label><%= t :symetry %></label>
<%= @gynecology_template.symetry %><br/>
<label><%= t :skin_abnormalities %></label>
<%= @gynecology_template.skin_abnormalities %><br/>
<label><%= t :nipple %></label>
<%= @gynecology_template.nipple %><br/>
<label><%= t :abnormal_mass %></label>
<%= @gynecology_template.abnormal_mass %><br/>
<label><%= t :axillary_region %></label>
<%= @gynecology_template.axillary_region %><br/>
<label><%= t :ganglion_growth %></label>
<%= @gynecology_template.ganglion_growth %><br/>
<label><%= t :abnormal_secretion %></label>
<%= @gynecology_template.abnormal_secretion %><br/>
<label><%= t :mastalgia %></label>
<%= @gynecology_template.mastalgia %><br/>

<h3><%= t :gynecological_exploration %></h3>
<label><%= t :external_aspect %></label>
<%= @gynecology_template.external_aspect %><br/>
<label><%= t :clitoris %></label>
<%= @gynecology_template.clitoris %><br/>
<label><%= t :vulva %></label>
<%= @gynecology_template.vulva %><br/>
<label><%= t :pubic_hair %></label>
<%= @gynecology_template.pubic_hair %><br/>
<label><%= t :himen %></label>
<%= @gynecology_template.himen %><br/>
<label><%= t :introito %></label>
<%= @gynecology_template.introito %><br/>
<label><%= t :perine %></label>
<%= @gynecology_template.perine %><br/>
<label><%= t :vaginal_walls %></label>
<%= @gynecology_template.vaginal_walls %><br/>
<label><%= t :secreation_and_discharge %></label>
<%= @gynecology_template.secreation_and_discharge %><br/>
<label><%= t :cervix %></label>
<%= @gynecology_template.cervix %><br/>
<label><%= t :uterus_position %></label>
<%= @gynecology_template.uterus_position %><br/>
<label><%= t :uterus_consistency %></label>
<%= @gynecology_template.uterus_consistency %><br/>
<label><%= t :uterus_size %></label>
<%= @gynecology_template.uterus_size %><br/>
<label><%= t :uterus_form %></label>
<%= @gynecology_template.uterus_form %><br/>
<label><%= t :annexes %></label>
<%= @gynecology_template.annexes %><br/>
<label><%= t :speculoscopy %></label>
<%= @gynecology_template.speculoscopy %><br/>
<label><%= t :internal_and_external_genitalia %></label>
<%= @gynecology_template.internal_and_external_genitalia %><br/>
<label><%= t :clinic_pelvimetry %></label>
<%= @gynecology_template.clinic_pelvimetry %><br/>
<label><%= t :impression_diagnosis %></label>
<%= @gynecology_template.impression_diagnosis %><br/>
<label><%= t :other_1%></label>
<%= @gynecology_template.other_1 %><br/>
<label><%= t :other_2 %></label>
<%= @gynecology_template.other_2 %><br/>
<label><%= t :other_3 %></label>
<%= @gynecology_template.other_3 %><br/>
<label><%= t :other_4 %></label>
<%= @gynecology_template.other_4 %><br/>
<label><%= t :other_5 %></label>
<%= @gynecology_template.other_5 %><br/>

<h3> Evolución de embarazo </h3>
<% @gynecology_template.pregnancy_evolutions.each do |pregnancy| %>
	Registro del día: <%= link_to pregnancy.created_at.to_date, [@gynecology_template, pregnancy] %><br/>
<% end %>


<h3> Notas especiales de evolución de embarazo </h3>
<% @gynecology_template.pregnancy_notes.each do |note| %>
	Nota del día: <%= link_to note.created_at.to_date, [@gynecology_template, note] %><br/>
<% end %>