config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors, controllers: {registrations: "doctors/registrations"} 

  root 'start#index'
 
  resources :doctors, only: [:show]

  get "autocomplete_patient_name", controller: "application"

  resources :patients, only: [:show]
  resources :invoices
  get 'search_patient'  => 'application#search_patient'
  post 'search_patient'  => 'application#search_patient'

  resources :ophtalmology_templates do
    resources :prescriptions, module: :ophtalmology_templates
    resources :template_photos, module: :ophtalmology_templates
    resources :template_files, module: :ophtalmology_templates
    resources :patients, module: :ophtalmology_templates
  end

  resources :general_templates do
    resources :general_annexes, except: [:index]
    resources :prescriptions, module: :general_templates
    resources :template_photos, module: :general_templates
    resources :template_files, module: :general_templates
    resources :patients, module: :general_templates
  end
  resources :gynecology_templates do
    resources :gynecology_annexes, except: [:index]
    resources :prescriptions, module: :gynecology_templates
    resources :template_photos, module: :gynecology_templates
    resources :template_files, module: :gynecology_templates
    resources :patients, module: :gynecology_templates
    resources :pregnancy_evolutions, except: [:index]
    resources :pregnancy_notes, except: [:index]
    
  end

  resources :doctors, only: [:show, :edit, :update, :destroy]
  resources :template_plans
  resources :plans, only: [:show] do
    collection do
      get :save_template_plan
      post :save_template_plan
    end
  end

  resources :payments, except: [:index, :show, :edit, :update, :destroy, :new, :create] do
    collection do
      get :accept
      put :accept
      get :cancel
      put :cancel
    end
  end
  get '/add_template_plan', to: "plans#add_template_plan", :as => "add_template_plan"
  get '/doctor_plan', to: "plans#doctor_plan", :as => "doctor_plan"
  get '/template_plan_history', to: "plans#template_plan_history", :as => "template_plan_history"

  get '/doctor_payment_panel', to: "doctors#doctor_payment_panel", :as => "doctor_payment_panel"
  get '/doctor_panel', to: "doctors#panel", :as => "doctor_panel"
  
  get '/admin_panel', to: "admins#admin_panel", :as => "admin_panel"
  get '/admin_templates_panel', to: "admins#admin_templates_panel", :as => "admin_templates_panel"
  get '/overdue_template_plans', to: "admins#overdue_template_plans", :as => "overdue_template_plans"
  get '/all_gynecologists', to: "admins#all_gynecologists", :as => "all_gynecologists"
  get '/all_ophthalmologists', to: "admins#all_ophthalmologists", :as => "all_ophthalmologists"
  get '/show_doctor', to: "admins#show_doctor", :as => "show_doctor"
  get '/show_invoice_data', to: "admins#show_invoice_data", :as => "show_invoice_data"

  resources :start, only: [:index]

end

app/models/general_template.rb
class GeneralTemplate < ActiveRecord::Base
	belongs_to :doctor

	has_one :patient, as: :templatable, dependent: :delete
	has_many :prescriptions, :as => :prescriptable, dependent: :delete_all
	has_many :template_photos, :as => :photable, dependent: :delete_all
	has_many :template_files, :as => :fileable, dependent: :delete_all
	has_many :general_annexes, dependent: :delete_all

	before_create :set_register_number


	private
		def set_register_number
			total_count = self.doctor.gynecology_templates.count
			self.register = total_count+1
		end
end

app/controllers/general_templates/prescription_controller.rb
class GeneralTemplates::PrescriptionsController < PrescriptionsController
  before_action :set_prescriptable
  
  private

    def set_prescriptable
      @prescriptable = GeneralTemplate.find(params[:general_template_id])
      authenticate_doctor_for_template(@prescriptable)
    end
end

app/controllers/general_templates/template_files_controller.rb
class GeneralTemplates::TemplateFilesController < TemplateFilesController
  before_action :set_fileable

  private

    def set_fileable
      @fileable = GeneralTemplate.find(params[:general_template_id])
      authenticate_doctor_for_template(@fileable)
    end
end

app/controllers/general_templates/template_photos_controller.rb
class GeneralTemplates::TemplatePhotosController < TemplatePhotosController
  before_action :set_photable

  private

    def set_photable
      @photable = GeneralTemplate.find(params[:general_template_id])
      authenticate_doctor_for_template(@photable)
    end
end

app/controllers/general_templates_controller.rb
class GeneralTemplatesController < ApplicationController
	before_action :authenticate_doctor!
	before_action :check_plan_limit, only: [:new, :create]
	before_action :check_payment_for_templates!
	before_action :set_general_template, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_doctor_for_general_template, only: [:show, :edit, :update, :destroy]
	before_action :find_patient, only: [:edit, :update]


	def index
		@general_templates = GeneralTemplate.where(doctor: current_doctor)
	end

	def new
		@general_template = GeneralTemplate.new
		
	end
	def create
		@general_template = GeneralTemplate.new(general_template_params)
		@general_template.doctor = current_doctor
		if @general_template.save
			Patient.create name: params[:general_template][:patients][:name], birth_date: params[:general_template][:patients][:birth_date], sex: params[:general_template][:patients][:sex], originary_from: params[:general_template][:patients][:originary_from], ocupation: params[:general_template][:patients][:ocupation], religion: params[:general_template][:patients][:religion], address: params[:general_template][:patients][:address], telephone: params[:general_template][:patients][:telephone], email: params[:general_template][:patients][:email], insurance_company: params[:general_template][:patients][:insurance_company], insurance_policy: params[:general_template][:patients][:insurance_policy], templatable_id: @general_template.id, templatable_type: "GeneralTemplate"
			flash[:notice] = "Expediente guardado."
			redirect_to @general_template
		else
			flash[:alert] = "Expediente no guardado. Vuelve a intentar en un rato." 
			render action: "new"
		end
	end

	def show
		#set_current_general_template(@general_template)
	end

	def edit
		
	end

	def update
		if @general_template.update(general_template_params)
			@patient.update_attributes( name: params[:general_template][:patients][:name], birth_date: params[:general_template][:patients][:birth_date], sex: params[:general_template][:patients][:sex], originary_from: params[:general_template][:patients][:originary_from], ocupation: params[:general_template][:patients][:ocupation], religion: params[:general_template][:patients][:religion], address: params[:general_template][:patients][:address], telephone: params[:general_template][:patients][:telephone], email: params[:general_template][:patients][:email], insurance_company: params[:general_template][:patients][:insurance_company], insurance_policy: params[:general_template][:patients][:insurance_policy])
			flash[:notice] = "Expediente guardado."
			redirect_to @general_template
		else
			flash[:alert] = "Expediente no guardado. Vuelve a intentar en un rato." 
			render action: "edit"
		end
	end

	def destroy 
		@general_template.destroy 
		flash[:notice] = "Expediente eliminado."
		redirect_to root_url
	end
	private
		def set_general_template
			@general_template = GeneralTemplate.find(params[:id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "Expediente inexistente."
			redirect_to root_url
		end

		def general_template_params
			params.require(:general_template).permit(:marital_status ,:reason,:mother_background,:father_background,:grandparents_background,:siblings_background,:parents_siblings_background,:children_background,:husband_background,:personal_background,:diet,:physical_exercise,:housing_perks,:smoking,:alergies,:drugs,:alcoholism,:inmunizations,:traumatics,:surgicals,:transfusions,:menarche,:gesta,:abortions,:rhythm,:pregnancies,:contraceptives,:last_period_date,:ivsa,:current_ailment,:cardio,:neuro,:gastro,:respiratory,:derma,:muscle,:urinary,:ta,:fc,:fr,:temperature,:weight,:size,:habitus,:head,:neck,:torax,:abdomen,:limbs ,:lab_results,:diagnosis,:treatment,:other_1,:other_2,:other_3,:other_4,:other_5
)
		end

		def find_patient
			@patient = Patient.find_by(templatable_id: @general_template.id, templatable_type: "GeneralTemplate")
		end	

		def check_plan_limit
			check_plan_limit_all_templates(current_doctor.general_templates.count)
		end

		def authenticate_doctor_for_general_template
			authenticate_doctor_for_elements(@general_template)
		end
end

app/helpers/general_templates_helper.rb
module GeneralTemplatesHelper
end

app/views/general_templates/edit.html.erb
<div class="center-content">
	<!-- <h4><%= t :new_expedient %></h4> -->
	<div class="form-container">
		<%= render 'form' %> 
	</div>
</div>

app/views/general_templates/index.html.erb
<h4><%= t :expedients %></h4>
<div id="patient-index">
	<a>
		<div class="patient-container">
			<div class="patient-name">
				<label><%= t :name %></label>
			</div>
			<div class="patient-ocupation">
				<label><%= t :ocupation %></label>
			</div>
			<div class="patient-birth-date">
				<label><%= t :birth_date %></label>
			</div>
			<div class="patient-telephone">
				<label><%= t :telephone %></label>
			</div>
		</div>
	</a>
	<% @general_templates.each do |expedient| %>
		<% expedient.id %>
		<% expedient.patients.each do |patient| %>
			<%= link_to expedient do %>
				<div class="patient-container">
					<div class="patient-name">
						<p><%= patient.name %></p>
					</div>
					<div class="patient-ocupation">
						<p><%= patient.ocupation %></p>
					</div>
					<div class="patient-birth-date">
						<p><%= patient.birth_date %></p>
					</div>
					<div class="patient-telephone">
						<p><%= patient.telephone %></p>
					</div>
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>
<%= javascript_include_tag "/assets/expedient/show" %>

app/views/general_templates/new.html.erb
<div class="center-content">
	<!-- <h4><%= t :new_expedient %></h4> -->
	<div class="form-container">
		<%= render 'form' %> 
	</div>
</div>

app/views/general_templates/show.html.erb
<label><%= t :register %></label>
<%= @general_template.register %><br/>

	<h1><%= @general_template.patient.name %></h1>
	<label><%= t :email %></label>
	<p><%= @general_template.patient.email %></p>
	<label><%= t :name %></label>
	<p><%= @general_template.patient.name %></p>
	<label><%= t :birth_date %></label>
	<p><%= @general_template.patient.birth_date %></p>
	<label><%= t :sex %></label>
	<p><%= @general_template.patient.sex %></p>
	<label><%= t :ocupation %></label>
	<p><%= @general_template.patient.ocupation %></p>
	<label><%= t :religion %></label>
	<p><%= @general_template.patient.religion %></p>
	<label><%= t :address %></label>
	<p><%= @general_template.patient.address %></p>
	<label><%= t :telephone %></label>
	<p><%= @general_template.patient.telephone %></p>
	<label><%= t :insurance_company %></label>
	<p><%= @general_template.patient.insurance_company %></p>
	<label><%= t :insurance_policy %></label>
	<p><%= @general_template.patient.insurance_policy %></p>


<%= link_to "Editar", edit_general_template_path(@general_template) %><br/>
<%= link_to "Eliminar", general_template_path(@general_template), method: :delete, data: {confirm: "¿Está seguro? Esta acción no se puede deshacer."} %><br/>

<%= link_to "Añadir Hoja de Evolución", new_general_template_general_annex_path(@general_template) %><br/>
<%= link_to "Añadir Receta",  new_general_template_prescription_path(@general_template)%><br/>

<%= render 'prescriptions/prescriptions', prescriptable: @general_template %>

<%= link_to "Añadir Foto",  new_general_template_template_photo_path(@general_template)%><br/>

<%= render 'template_photos/template_photos', photable: @general_template %>


<%= link_to "Añadir Archivo",  new_general_template_template_file_path(@general_template)%><br/>

<%= render 'template_files/template_files', fileable: @general_template %>


<h2>Historia Clínica</h2>



<label><%= t :marital_status %></label>
<%= @general_template.marital_status %><br/>

<label><%= t :reason%></label>
<%= @general_template.reason %><br/>

<h3><%= t :family_background %></h3>
<label><%= t :mother_background %></label>
<%= @general_template.mother_background %><br/>
<label><%= t :father_background %></label>
<%= @general_template.father_background %><br/>
<label><%= t :grandparents_background %></label>
<%= @general_template.grandparents_background %><br/>
<label><%= t :siblings_background %></label>
<%= @general_template.siblings_background %><br/>
<label><%= t :parents_siblings_background %></label>
<%= @general_template.parents_siblings_background %><br/>
<label><%= t :children_background %></label>
<%= @general_template.children_background %><br/>
<label><%= t :husband_background %></label>
<%= @general_template.husband_background %><br/>
<label><%= t :personal_background %></label>
<%= @general_template.personal_background %><br/>

<h3>Antecedentes Personales no Patólogicos</h3>
<label><%= t :diet %></label>
<%= @general_template.diet %><br/>
<label><%= t :smoking %></label>
<%= @general_template.smoking %><br/>
<label><%= t :alergies %></label>
<%= @general_template.alergies %><br/>
<label><%= t :drugs %></label>
<%= @general_template.drugs %><br/>
<label><%= t :alcoholism %></label>
<%= @general_template.alcoholism %><br/>
<label><%= t :inmunizations %></label>
<%= @general_template.inmunizations %><br/>

<h3>Antecedentes Personales Patólogicos</h3>
<label><%= t :traumatics %></label>
<%= @general_template.traumatics %><br/>
<label><%= t :surgicals %></label>
<%= @general_template.surgicals %><br/>
<label><%= t :transfusions %></label>
<%= @general_template.transfusions %><br/>

<h3><%= t :physical_exploration %></h3>
<label><%= t :ta %></label>
<%= @general_template.ta %><br/>
<label><%= t :fc %></label>
<%= @general_template.fc %><br/>
<label><%= t :fr %></label>
<%= @general_template.fr %><br/>
<label><%= t :temperature %></label>
<%= @general_template.temperature %><br/>
<label><%= t :weight %></label>
<%= @general_template.weight %><br/>
<label><%= t :size %></label>
<%= @general_template.size %><br/>
<label><%= t :habitus %></label>
<%= @general_template.habitus %><br/>
<label><%= t :head %></label>
<%= @general_template.head %><br/>
<label><%= t :neck %></label>
<%= @general_template.neck %><br/>
<label><%= t :torax %></label>
<%= @general_template.torax %><br/>
<label><%= t :abdomen %></label>
<%= @general_template.abdomen %><br/>
<label><%= t :limbs %></label>
<%= @general_template.limbs %><br/>
     

<h3><%= t :gynecological_background %></h3>
<label><%= t :menarche%></label>
<%= @general_template.menarche %><br/>
<label><%= t :rhythm %></label>
<%= @general_template.rhythm %><br/>
<label><%= t :pregnancies %></label>
<%= @general_template.pregnancies %><br/> 
<label><%= t :gesta %></label>
<%= @general_template.gesta %><br/> 
<label><%= t :abortions %></label>
<%= @general_template.abortions %><br/> 
<label><%= t :contraceptives %></label>
<%= @general_template.contraceptives %><br/> 
<label><%= t :ivsa %></label>
<%= @general_template.ivsa %><br/>
<label><%= t :last_period_date %></label>
<%= @general_template.last_period_date %><br/>

<h3><%= t :current_ailment %></h3>
<%= @general_template.current_ailment %><br/>

<h3>Interrogatorio por aparatos y sistemas</h3>
<label><%= t :cardio %></label>
<%= @general_template.cardio %><br/>
<label><%= t :neuro %></label>
<%= @general_template.neuro %><br/>
<label><%= t :gastro %></label>
<%= @general_template.gastro %><br/>
<label><%= t :respiratory %></label>
<%= @general_template.respiratory %><br/>
<label><%= t :derma %></label>
<%= @general_template.derma %><br/>
<label><%= t :muscle %></label>
<%= @general_template.muscle %><br/>
<label><%= t :urinary %></label>
<%= @general_template.urinary %><br/>


<h3><%= t :lab_results %></h3>
<%= @general_template.lab_results %><br/>

<h3><%= t :diagnosis %></h3>
<%= @general_template.diagnosis %><br/>

<h3><%= t :treatment %></h3>
<%= @general_template.treatment %><br/>

<label><%= t :other_1%></label>
<%= @general_template.other_1 %><br/>
<label><%= t :other_2 %></label>
<%= @general_template.other_2 %><br/>
<label><%= t :other_3 %></label>
<%= @general_template.other_3 %><br/>
<label><%= t :other_4 %></label>
<%= @general_template.other_4 %><br/>
<label><%= t :other_5 %></label>
<%= @general_template.other_5 %><br/>