config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors, controllers: {registrations: "doctors/registrations"} 

  root 'start#index'
 
  resources :doctors, only: [:show]

  get "autocomplete_patient_name", controller: "application"

  resources :patients, only: [:show]
  resources :invoices
  get 'search_patient'  => 'application#search_patient'
  post 'search_patient'  => 'application#search_patient'

  resources :ophtalmology_templates do
    resources :prescriptions, module: :ophtalmology_templates
    resources :template_photos, module: :ophtalmology_templates
    resources :template_files, module: :ophtalmology_templates
    resources :patients, module: :ophtalmology_templates
  end

  resources :general_templates do
    resources :general_annexes, except: [:index]
    resources :prescriptions, module: :general_templates
    resources :template_photos, module: :general_templates
    resources :template_files, module: :general_templates
    resources :patients, module: :general_templates
  end
  resources :gynecology_templates do
    resources :gynecology_annexes, except: [:index]
    resources :prescriptions, module: :gynecology_templates
    resources :template_photos, module: :gynecology_templates
    resources :template_files, module: :gynecology_templates
    resources :patients, module: :gynecology_templates
    resources :pregnancy_evolutions, except: [:index]
    resources :pregnancy_notes, except: [:index]
    
  end

  resources :doctors, only: [:show, :edit, :update, :destroy]
  resources :template_plans
  resources :plans, only: [:show] do
    collection do
      get :save_template_plan
      post :save_template_plan
    end
  end

  resources :payments, except: [:index, :show, :edit, :update, :destroy, :new, :create] do
    collection do
      get :accept
      put :accept
      get :cancel
      put :cancel
    end
  end
  get '/add_template_plan', to: "plans#add_template_plan", :as => "add_template_plan"
  get '/doctor_plan', to: "plans#doctor_plan", :as => "doctor_plan"
  get '/template_plan_history', to: "plans#template_plan_history", :as => "template_plan_history"

  get '/doctor_payment_panel', to: "doctors#doctor_payment_panel", :as => "doctor_payment_panel"
  get '/doctor_panel', to: "doctors#panel", :as => "doctor_panel"
  
  get '/admin_panel', to: "admins#admin_panel", :as => "admin_panel"
  get '/admin_templates_panel', to: "admins#admin_templates_panel", :as => "admin_templates_panel"
  get '/overdue_template_plans', to: "admins#overdue_template_plans", :as => "overdue_template_plans"
  get '/all_gynecologists', to: "admins#all_gynecologists", :as => "all_gynecologists"
  get '/all_ophthalmologists', to: "admins#all_ophthalmologists", :as => "all_ophthalmologists"
  get '/show_doctor', to: "admins#show_doctor", :as => "show_doctor"
  get '/show_invoice_data', to: "admins#show_invoice_data", :as => "show_invoice_data"

  resources :start, only: [:index]

end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :doctor
	has_many :payments
	has_many :plan_elements
  	has_many :template_plan, :through => :plan_elements, :source => :element, :source_type => 'TemplatePlan'
  	has_many :site_plan, :through => :plan_elements, :source => :element, :source_type => 'SitePlan'
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
	before_action :set_plan, only: [:show, :edit, :update, :destroy]


	def save_template_plan
		@plan = Plan.new
		if admin_signed_in?
			@plan.doctor = Doctor.find(params[:doctor_id])
		else
			@plan.doctor = current_doctor
		end
		@plan.billing_frequency = params[:billing_frequency]
		@plan.billing_preference = params[:billing_preference]
		if params[:active] 
			@plan.active = 1

		else
			@plan.active = -4
			@plan.grace_til = Date.today + 15.days
		end
		
		@plan.valid_from = Date.today
		
		
		@template_plan = TemplatePlan.find(params[:template_id])
		

		if @plan.save
			@plans = Plan.where(doctor: @plan.doctor)
			@plans.each do |plan|
				plan.plan_elements.each do |element| 
					if element.element_type == "TemplatePlan"
						plan.update_attributes(active: -3)
					end
				end
			end

			@plan.plan_elements.create(element: @template_plan)

			case params[:billing_frequency] 
				when "Mensual"
					Payment.create(next_payment: Date.today, plan: @plan, accepted_payment: false, payment_number: 1)
				when "Semestral"
					Payment.create(next_payment: Date.today, plan: @plan, accepted_payment: false, payment_number: 1)
				when "Anual"
					Payment.create(next_payment: Date.today, plan: @plan, accepted_payment: false, payment_number: 1)
					
			end

			flash[:notice] = "Plan guardado."
			if admin_signed_in?
				redirect_to @plan
			else
				redirect_to doctor_plan_path
			end
		else
			flash[:alert] = "Plan no guardado. Vuelve a intentar en un rato." 
			render action: "new"
		end
	end

	def show
	end

	def doctor_plan
		@plan = Plan.find(params[:format])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "Plan inexistente."
			redirect_to root_url
	end
	def template_plan_history
		@doctor =  Doctor.find(params[:format])
		@inactive_plans = Plan.where("doctor_id = ? AND active = ?", @doctor, -3)
	end

	
	private
		def set_plan
			@plan = Plan.find(params[:id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "Plan inexistente."
			redirect_to root_url
		end

		def plan_params
			params.require(:plan).permit(:valid_til, :billing_frequency, :billing_preference)
		end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/add_template_plan.html.erb
<%= form_tag(:action => 'save_template_plan') do %>
	
	<% if admin_signed_in? %>
		Doctor: <%= select_tag "doctor_id", options_for_select(Doctor.all.collect{ |u| [u.name, u.id]} ) %><br/>
		¿Activar Plan? <%= check_box_tag "active" %>
	<% end %>
	Plan: <%= select_tag "template_id", options_for_select(TemplatePlan.all.collect{ |u| [u.name, u.id]} ) %><br/>

	<div>Al escoger el pago semestral o anual se aplica un descuento del 30% </div>
	Frecuencia de Pago: <%= select_tag "billing_frequency", options_for_select([ "Mensual", "Semestral", "Anual" ], "Mensual") %><br/>
	Preferencia: <%= select_tag "billing_preference", options_for_select([ "Paypal", "Recoger en Consultorio", "Déposito Bancario", "Transferencia Electrónica", "Déposito en OXXO" ], "Paypal") %><br/>
	<%= submit_tag "Guardar" %>
<% end %>

app/views/plans/doctor_plan.html.erb
<h1>Plan de <%= @plan.doctor.name %></h1>

<% case @plan.active %>
	<% when 1 %>
		<p>Status: Activo</p>
	<% when 0 %>
		<p>Status: Verificando Pago</p>
	<% when -1 %>
		<p>Status: Inactivo por falta de pago</p>
	<% when -3 %>
		<p>Status: Inactivo/Plan anterior</p>

<% end %>
<% @plan.plan_elements.each do |element| %>
		<%= element.element.name %><br/>
		<% case @plan.billing_frequency %>
			<% when "Mensual" %>
				Importe: <%= element.element.monthly_cost %><br/>
			<% when "Semestral" %>
				Importe: <%= element.element.anual_cost / 2%><br/>
			<% when "Anual" %>
				Importe: <%= element.element.anual_cost %><br/>
		<% end %>
		
<% end %>
Activo desde: <%= @plan.created_at.to_date %><br/>
Frecuencia de pago: <%= @plan.billing_frequency %><br/>
Preferencia de pago: <%= @plan.billing_preference %><br/>
 
 <h3>Pagos Pendientes y/o próximos</h3>

<p>Si ya pagaste, no te preocupes, estamos en proceso de confirmar el pago, te notificaremos cuando lo hayamos realizado.</p>.
<% @plan.payments.each do |payment| %>
	<% if !payment.accepted_payment? %>
		Pago del <%= payment.next_payment %> </br>
		<% end %>
<% end %>

<h3>Historial de pagos</h3>

<p>Estos son los pagos que has realizado.</p>

<% @plan.payments.each do |payment| %>
	<% if payment.accepted_payment? %>
		Pagado el <%= payment.updated_at %>, pago de <%= payment.next_payment %> </br>
		<% end %>
<% end %>

app/views/plans/edit.html.erb
<%= form_for(@plan) do |f| %>

	<% @plan.plan_elements.each do |element| %>
		<% if element.element_type == "TemplatePlan" %>
			Plan: <%= select_tag "template_id", options_for_select(TemplatePlan.all.collect{ |u| [u.name, u.id]} ) %><br/>
		<% end %>
	<% end %>
	



	<div>Al escoger el pago semestral o anual se aplica un descuento del 30% </div>

	Frecuencia de Pago: <%= select_tag "billing_frequency", options_for_select([ "Mensual", "Semestral", "Anual" ], "Mensual") %><br/>
	Preferencia: <%= select_tag "billing_preference", options_for_select([ "Paypal", "Recoger en Consultorio", "Déposito Bancario", "Transferencia Electrónica", "Déposito en OXXO" ], "Paypal") %><br/>
	<%= submit_tag "Guardar" %>
<% end %>

app/views/plans/show.html.erb
<h1>Plan de <%= @plan.doctor.name %></h1>

<% case @plan.active %>
	<% when 1 %>
		<p>Status: Activo</p>
	<% when -4 %>
		<p>Status: Verificando Pago</p>
	<% when -1 %>
		<p>Status: Inactivo por falta de pago</p>
	<% when -3 %>
		<p>Status: Inactivo/Plan anterior</p>

<% end %>
<% @plan.plan_elements.each do |element| %>
		<%= element.element.name %><br/>
		<% case @plan.billing_frequency %>
			<% when "Mensual" %>
				Importe: <%= element.element.monthly_cost %><br/>
			<% when "Semestral" %>
				Importe: <%= element.element.anual_cost / 2%><br/>
			<% when "Anual" %>
				Importe: <%= element.element.anual_cost %><br/>
		<% end %>
		
<% end %>
Activo desde: <%= @plan.created_at.to_date %><br/>
Frecuencia de pago: <%= @plan.billing_frequency %><br/>
Preferencia de pago: <%= @plan.billing_preference %><br/>
 
 <h3>Pagos Pendientes y/o próximos</h3>

<% @plan.payments.each do |payment| %>
	<% if !payment.accepted_payment? %>
		El <%= payment.next_payment %> | <%= link_to "Confirmar Pago", accept_payments_path(payment) %>| <%= link_to "Denegar Pago", cancel_payments_path(payment) %></br>
		<% end %>
<% end %>

<h3>Historial de pagos</h3>

<p>Si cancelas el pago se cancelará también el plan del doctor</p>

<% @plan.payments.each do |payment| %>
	<% if payment.accepted_payment? %>
		Pagado el <%= payment.updated_at %>, pago de <%= payment.next_payment %> | <%= link_to "Cancelar Pago", cancel_payments_path(payment) %></br>
		<% end %>
<% end %>

app/views/plans/template_plan_history.html.erb
 <h1>Planes Inactivos de: <%= @doctor.name %></h1>
 <% @inactive_plans.each do |plan| %>
	<% plan.plan_elements.each do |element| %>
		<% if element.element_type == "TemplatePlan" %>
			<%= link_to element.element.name, plan %>. Del <%= plan.created_at.to_date %> al <%= plan.valid_til %><br/>
		<% end %>
	<% end %>
<% end %>